version: '3'

services:
  djnago_app:
    build: .
    env_file:
      -  .env

    volumes:
      - static_vol:/app/sub_app/static
      - media_vol:/app/sub_app/media
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static_vol:/app/sub_app/static
      - media_vol:/app/sub_app/media
    ports:
      - "8080:80"
    depends_on:
      - djnago_app
      
volumes:
  static_vol:
  media_vol: